- name: Enable firewalld service
  systemd:
    service: firewalld
    enabled: "{{ firewalld_state }}"
  #when: (ansible_os_family == "RedHat")

- name: Start firewalld service
  systemd:
    service: firewalld
    state: restarted
  #when: (  == "RedHat") and
  #      ( firewalld_state == 'yes')
  when: ( firewalld_state == 'yes')

- name: Open ports on deployers firewall
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - "{{ firewall_deployer_ports }}"
 # when: (ansible_os_family == "RedHat") and
 #       ( firewalld_state == 'yes')
  when: ( firewalld_state == 'yes') and (inventory_hostname in groups['deployers'])
  notify: Firewalld restart

- name: Open ports on search heads nodes firewall
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - "{{ firewall_sh_nodes_ports }}"
 # when: (ansible_os_family == "RedHat") and
 #       ( firewalld_state == 'yes')
  when: ( firewalld_state == 'yes') and (inventory_hostname in groups['sh_nodes'])
  notify: Firewalld restart

- name: Install Splunk
  yum:
     name: "{{ item }}"
     state: present
  with_items:
   - "{{ splunk_packages_rpm }}" 
  #when: (ansible_os_family == "RedHat")

- name: Preparing Admin user config
  template:
    src: ./templates/user-seed.conf.admin.j2
    dest: "{{ splunk_base_path }}/etc/system/local/user-seed.conf"
    owner: splunk
    group: splunk
    mode: '0750'

- name: First start Splunk
  command: "./splunk start --accept-license --no-prompt --answer-yes"
  args:
    chdir: "{{ splunk_base_path }}/bin"

- name: Enable splunk on boot
  command: "./splunk enable boot-start"
  args:
    chdir: "{{ splunk_base_path }}/bin"

- name: Set credentials for clustering
  template:
    src: ./templates/server.conf.j2
    dest: "{{ splunk_base_path }}/etc/system/local/server.conf"
    owner: splunk
    group: splunk
    mode: '0750'
  when: inventory_hostname in groups['deployers']
  tags: 
    - deployer_init

- name: Restart splunk
  command: "./splunk restart"
  args:
    chdir: "{{ splunk_base_path }}/bin"
  when: inventory_hostname in groups['deployers']
  tags: 
    - deployer_init