## FIREWALL
firewall_deployer_ports:
 - 80
 - 88
 - 89
 - 8000
 - 8065
 - 8080
 - 8089
 - 8191

firewall_sh_nodes_ports:
 - 80
 - 8065
 - 8080
 - 8089
 - 8191
 - 34567

firewalld_state: 'yes'

## SPLUNK
splunk_packages_rpm:
 - /tmp/splunk-7.1.2-a0c72a66db66-linux-2.6-x86_64.rpm

splunk_base_path: '/opt/splunk'

splunk_admin_username: 'admin'
splunk_admin_hashed_password: '$6$0K61gvg5nYUYUYvh$9c9/4iF445cnN7E5lvj0H4w6jnWtOgtgcJnYuMjwV7OlFzStLn32zLVkSHT8CUccYFXoYmZHC2T4t5sRfYvh80'

splunk_credentials: 'admin:Splunky##!'

## Search heads cluster

sh_cluster_password: 'hg2qwe1l'
sh_cluster_label: 'shcluster_tst'

deployer_address: "https://{{ hostvars[groups['deployers'][0]]['ansible_default_ipv4']['address'] }}:8089"
sh_node_address: "https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8089"
replication_port_value: '34567'
replication_factor_value: '2'

sh_servers_list: '"https://10.200.6.72:8089,https://10.200.6.76:8089,https://10.200.6.83:8089"'

 #"https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8089"

#sh_servers_list: "{{ groups['sh_nodes'] | map('extract', hostvars, ['ansible_ssh_host']) | join(':8089,') }}:8089"



