## FIREWALL
firewall_deployer_ports:
 - 80
 - 88
 - 89
 - 8000
 - 8065
 - 8080
 - 8089
 - 8191

firewall_sh_nodes_ports:
 - 80
 - 8065
 - 8080
 - 8089
 - 8191
 - 34567

firewalld_state: 'yes'

## SPLUNK
splunk_packages_rpm:
 - /tmp/splunk-7.1.2-a0c72a66db66-linux-2.6-x86_64.rpm

splunk_base_path: '/opt/splunk'

splunk_admin_username: 'admin'
splunk_admin_hashed_password: '$6$0K61gvg5nYUYUYvh$9c9/4iF445cnN7E5lvj0H4w6jnWtOgtgcJnYuMjwV7OlFzStLn32zLVkSHT8CUccYFXoYmZHC2T4t5sRfYvh80'

splunk_credentials: 'admin:Splunky##!'

## Search heads cluster

sh_cluster_password: 'hg2qwe1l'
sh_cluster_label: 'shcluster_tst'

#master_address: {{ https://group[masters][0].ansible_host:8089 }}