- name: Test ping
  ping:

- name: Check if firewalld package is installed (on RHEL).
  shell: yum list installed firewalld
  args:
    warn: false
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
#when: ansible_os_family == "RedHat" and firewall_disable_firewalld

- name: open tcp 80
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

- name: open tcp 88
  firewalld:
    port: 88/tcp
    permanent: true
    state: enabled

- name: open tcp 89
  firewalld:
    port: 89/tcp
    permanent: true
    state: enabled

- name: open tcp 8000
  firewalld:
    port: 8000/tcp
    permanent: true
    state: enabled

- name: open tcp 8089
  firewalld:
    port: 8089/tcp
    permanent: true
    state: enabled

- name: open tcp 8065
  firewalld:
    port: 8065/tcp
    permanent: true
    state: enabled

- name: open tcp 8080
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled

- name: open tcp 8191
  firewalld:
    port: 8191/tcp
    permanent: true
    state: enabled

- name: open tcp 9997
  firewalld:
    port: 9997/tcp
    permanent: true
    state: enabled

#- name: copy splunk rpm file to server
#  copy:
#     src: package.rpm
#     dest: /tmp/splunk-7.1.2-a0c72a66db66-linux-2.6-x86_64.rpm

- name: install splunk package
  yum:
     name: /tmp/splunk-7.1.2-a0c72a66db66-linux-2.6-x86_64.rpm
     state: present

- name: start splunk
  command: ./splunk start --accept-license -auth admin:Splunky##! arg1
  args:
    chdir: /opt/splunk/bin/
  register: splunk-start

- name: enable splunk on boot
  command: /opt/splunk/bin/splunk enable boot-start
  register: splunk-enable

#- name: add slave to cluster
#  command: /opt/splunk/bin/splunk edit cluster-config -mode slave -master_uri https://10.200.7.102:8089 -replication_port 9997 -secret TestSplunkInstallation -auth admin:Splunky##!
#  register: add slave

- name: restart splunk
  command: /opt/splunk/bin/splunk restart
  register: splunk-restart
